edition = "2024"
style_edition = "2024"
unstable_features = true
brace_style = "SameLineWhere"
max_width = 140
array_width = 100
imports_layout = "Vertical"
blank_lines_upper_bound = 2
trailing_comma = "Vertical"